CREATE TABLE IF NOT EXISTS Department (
	id SERIAL PRIMARY KEY, 
	dep_name VARCHAR(80) NOT NULL UNIQUE,
	head VARCHAR(60) NOT NULL UNIQUE
	);


CREATE TABLE IF NOT EXISTS Employee (
	name VARCHAR(60) PRIMARY KEY, 
	department_id INTEGER NOT NULL REFERENCES Department(id)
	);
	